#!/bin/sh

DATADIR=data

mkdir -p $DATADIR/testvol

rm -f $DATADIR/master.db
sqlite3 $DATADIR/master.db < $top_srcdir/mk-storagedb.sql

if [ ! -f $DATADIR/master.db ]
then
	rm -rf $DATADIR
	echo "test database not found."
	exit 1
fi

if [ ! -f ssl-cert.pem ]
then
	cp $top_srcdir/test/ssl-cert.pem .
	touch ssl-cert.pem.copied
fi

if [ ! -f ssl-key.pem ]
then
	cp $top_srcdir/test/ssl-key.pem .
	touch ssl-key.pem.copied
fi

exit 0
