#!/bin/sh

if [ -f cld1.pid -o -f cld2.pid -o -f cld3.pid ]
then
	echo "pid file found.  daemons still running?"
	exit 1
fi

## Static port
# ../server/cld -P cld.pid -d "$PWD/data" -p 18181 --port-file=cld.port -E
## Dynamic port
../server/cld -P cld1.pid -d "$PWD/data/n1/data" -p auto --port-file=cld1.port \
	-E -D 2 -S 3			\
	-m localhost.localdomain	\
	-R localhost.localdomain:19182	\
	-R localhost.localdomain:19183
../server/cld -P cld2.pid -d "$PWD/data/n2/data" -p auto --port-file=cld2.port \
	-E -D 2 -S 3			\
	-m localhost.localdomain	\
	-R localhost.localdomain:19181	\
	-R localhost.localdomain:19183
../server/cld -P cld3.pid -d "$PWD/data/n3/data" -p auto --port-file=cld3.port \
	-E -D 2 -S 3			\
	-m localhost.localdomain	\
	-R localhost.localdomain:19181	\
	-R localhost.localdomain:19182
sleep 1

echo "      start-daemon: Waiting 20s, for daemons to start up..."
sleep 20

exit 0
