#!/bin/sh

if [ -f cld.pid ]
then
	echo "cld.pid file found.  daemon still running?"
	exit 1
fi
if [ -f chunkd.pid ]
then
	echo "chunkd.pid file found.  daemon still running?"
	exit 1
fi

# May be different on Solaris... like /usr/libexec or such.
/usr/sbin/cld -d data/cld -P cld.pid -p 18081

../server/chunkd -f $top_srcdir/test/server-test.cfg $*

sleep 3

exit 0
