#!/bin/sh

if [ -f cld.pid ]
then
	echo "pid file found.  daemon still running?"
	exit 1
fi

## Static port
# cldport=18181
# echo $cldport > cld.port
# ../server/cld -P cld.pid -d "$PWD/data" -p $cldport -E
## Dynamic port
../server/cld -P cld.pid -d "$PWD/data" --port-file=cld.port -E

sleep 3

exit 0
