#!/bin/sh

if [ ! -f cld.pid ]
then
	echo no daemon pid file found.
	exit 1
fi

kill `cat cld.pid`

for n in 0 1 2 3 4 5 6 7 8 9
do
	if [ ! -f cld.pid ]
	then
		exit 0
	fi

	sleep 1
done

echo "PID file not removed, after signal sent."
rm -f cld.pid
exit 1
