#!/bin/sh

if [ -f cld.pid ]
then
	echo "pid file found.  daemon still running?"
	exit 1
fi

## Static port
# ../../cld/cld -P cld.pid -d "$PWD/data" -p 18181 --port-file=cld.port -E
## Dynamic port
../../cld/cld -P cld.pid -d "$PWD/data" -p auto --port-file=cld.port -E

sleep 3

exit 0
